import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { cn } from '@/lib/utils'
import Navbar from '@/components/Navbar'
import './globals.css'
import { Footer } from '@/components'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn('h-full font-sans antialiased bg-primary-foreground', inter.className)}>
        <main className="relative flex flex-col min-h-screen">
          <Navbar />
          <div className="flex-grow flex-1 -mt-20 overflow-hidden">
            {children}
          </div>
          <Footer />
        </main>
      </body>
    </html>
  )
}
